### PR TITLE
Address hasBlock deprecation: update to has-block

### PR DESCRIPTION
**Pull request by sacarino**
Fix to issue https://github.com/kaliber5/ember-bootstrap-power-select/issues/297

### CODE REVIEW

**Review by jelhan — APPROVED** [review]
Thanks a lot.

Wondering why CI isn't running. Also I don't see a button to approve it. Will try to find some time tomorrow to look into it.

**Comment by jelhan** [comment]
> Wondering why CI isn't running. Also I don't see a button to approve it. Will try to find some time tomorrow to look into it.

It is confusing. CI seems to work for pull requests created by myself. But I also do not see the button to approve the CI for your public fork. :confused:

**Comment by sacarino** [comment]
Odd.

I guess if push comes to shove, you could edit the two templates directly
in GitHub to create a new branch and trigger the CI.

**Comment by jelhan** [comment]
Do not mind. The changes here shouldn't be critical. I will merge them without CI and see the result afterwards. Currently trying to get project into a working state again so that I can release it afterwards.

**Comment by jelhan** [comment]
@sacarino Do you need this urgently? I would like to make sure that it is working with Ember v4 as well as with latest versions of Ember Bootstrap and Ember Power Select before releasing a new major. But could do a release candidate if you have urgent need to use it in your project.

**Comment by sacarino** [comment]
Not urgent at all. I was just looking to clean up our build logs.

**Pull request merged**
