### PR TITLE
Support for power select multiple.

### PR DESCRIPTION
**Pull request by mwisner**
This PR adds support for the power-select-multiple component provided by the power-select ember addon. 

-- Added power-select-multiple component
-- Added tests for component
-- Added power-select-multiple to dummy app
-- Upgraded packages

### CODE REVIEW

**Comment by simonihmig** [comment]
Hey @mwisner, thanks for working on this in advance! Just ping once this is ready for review! 😃

**Comment by mwisner** [comment]
Hey @simonihmig tests and dummy app are updated. 

Couple of extra things. I also went through and upgraded a number of packages, including ember to 2.14. If you'd like me to revert any of those please let me know. I also added some fieldsets and a few other minor things to the dummy app, again if those aren't appropriate just let me know and I will remove.

**Comment by simonihmig** [comment]
@mwisner that looks great! Just one missing piece: could you please provide some simple usage examples to the README? That would be awesome!

**Comment by mwisner** [comment]
Hi @simonihmig, apologies for taking so long on this! My week kind of got away from me. 

I took a stab at adding an example to the readme but i'm not sure if it makes sense. Do you have any recommendations or preferences with this? I could probably break out the single select vs multi select usage examples a little more but they are so similar I wasn't sure if it would make sense to duplicate all of that.

**Comment by simonihmig** [comment]
@mwisner sorry for the delay here. This looks great, thanks again for contributing this!

**Pull request merged**
